#pragma config(Motor,  port1,           rightMotorUp,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotorDown, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotorUp,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftMotorDown, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           middleMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true) {

    motor[rightMotorUp] = vexRT[Ch2];
    motor[rightMotorDown] = vexRT[Ch2];
    motor[leftMotorUp] = vexRT[Ch3];
    motor[leftMotorDown] = vexRT[Ch3];
    motor[middleMotor] = vexRT[Ch4];

  }

}
