#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port1,           rightFrontWheel, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightBackWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftFrontWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBackWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           middleWheel,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           fourbarLeft,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           fourbarRight,  tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void drivestraight(int distance){
while(true){
  while (SensorValue[drivestraight] < distance){


    motor[rightFrontWheel] = 127;
    motor[rightBackWheel] = 127;
    motor[leftFrontWheel] = 127;
    motor[leftBackWheel] = 127;
    motor[middleWheel] = 127;
   }
     if(SensorValue[drivestraight] > distance){
         motor[rightFrontWheel] = 0;
    motor[rightBackWheel] = 0;
    motor[leftFrontWheel] = 0;
    motor[leftBackWheel] = 0;
    motor[middleWheel] = 0;
  }
}
}


task autonomous(){




  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

 while(true)
  if(vexRT[Btn7U] == 1){
    bool preset = true;
    if (preset = true && SensorValue[potentiometer] < 100) {








    motor[fourbarLeft] = 127;
    motor[fourbarRight] = 127;
      if(SensorValue[potentiometer] = 900)
        motor[fourbarLeft] = 127








task usercontrol()
{
  while(true)
  {
    if (vexRT[Btn5D] ==  1) {
      motor[fourbarLeft] = -127;
      motor[fourbarRight] = -127;
   }
   else if (vexRT[Btn5U] == 1) {
      motor[fourbarLeft] = 127;
      motor[fourbarRight] = 127;
   }
   else {
     motor[fourbarLeft] = 0;
     motor[fourbarRight] = 0;
  }

  //Drive Train
    motor[rightFrontWheel] = vexRT[Ch3];
    motor[rightBackWheel] = vexRT[Ch3];
    motor[leftFrontWheel] = vexRT[Ch3];
    motor[leftBackWheel] = vexRT[Ch3];
    motor[middleWheel] = vexRT[Ch4];



    //Motors
    while(true){
    motor[fourbarLeft] = vexRT[Ch2];
    motor[fourbarRight] = vexRT[Ch2];
   }
  }
}
